project:
  type: website

publish:
  gh-pages:
    branch: gh-pages    # GitHub Pages 通常使用这个分支发布
    orphan: true        # 使用孤立的 gh-pages 分支

website:
  title: "Alix"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



